### ISSUE TITLE
DRS Starter Kit - Update the documentation

### ISSUE THREAD

**Issue by RegganThomas** [ga4gh/ga4gh-starter-kit-drs#74]
asap: update the documentation to clarify it does *not* match DRS 1.1 (or any other published API version)
soon: flag the POST methods as out-of-spec, including renaming them for clarity
when possible: reconcile with DRS 1.3/1.4 once they're out (specifically with #381 and #365)
@yash-puligundla

**Comment by dglazer** [comment]
Yash, feel free to ask @ianfore or @dglazer if you want more context.

**Comment by ianfore** [comment]
Version reported by service-info is 1.1 - so that should also be addressed.

**Comment by yash-puligundla** [comment]
@ianfore @dglazer Since there are features implemented from the v1.3 draft, would it be fine to call it **1.3draft**  in the documentation and the service info for the time being? 
We will revisit this once version 1.3 is released to make sure the starter kit adheres to the changes.

**Comment by dglazer** [comment]
Ian has looked more closely, but I *believe* the SK implementation
implements a mix of 1.1, 1.3 draft, and not-in-any-official-version
functionality.

**Comment by yash-puligundla** [comment]
Which of these would you prefer for the version returned by the service-info endpoint?

- 1.3draft
- 1.3beta
- test

**Comment by dglazer** [comment]
My vote -- either "test" or "1.3experimental".

**Comment by ianfore** [comment]
I think 1.3experimental has the right tone, and honors what the implementation does. StarterKit DRS helps us with an executable experimental implementation of what has been discussed over the last year or more. It shouldn't be taken as canonical, but was grounded in and driven by those discussions, and a wish to move things forward. Kudos!

I hope we can use the StarterKit as is in our efforts to land 1.3 where it helps illustrate what 1.3/1.4 might do.

Pre-plenary I began to explore how we can use the bulk request capability to show how it will complement bundle deprecation, and provide for the underlying need in bundles via what we believe will be a more suitable, and more flexible route. I hope we can still do that.

**Comment by yash-puligundla** [comment]
Great! Thank you both. I agree that "1.3experimental" suits better. I will update the documentation and service-info to reflect the same.

> Pre-plenary I began to explore how we can use the bulk request capability to show how it will complement bundle deprecation, and provide for the underlying need in bundles via what we believe will be a more suitable, and more flexible route. I hope we can still do that.

@ianfore, Even after the starter kit is updated to match the most recent DRS release, you should still be able to do this using an [older release of the DRS starter kit](https://github.com/ga4gh/ga4gh-starter-kit-drs/tags) in the GitHub repo.

**Comment by yash-puligundla** [comment]
The documentation and service-info response are changed to reflect the DRS specification version as `1.3.0experimental`. 
I have also added a note to the README that this version of the starter kit does not comply with any released DRS versions.
